language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - composer phpstan
  - composer test
